server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  # errorStack: false

logger:
  level : "all"
  stdout: true  

database:
  default:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    pass: "root"
    name: "default"
    type: "mysql"