// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"test-gf/internal/model"
	"test-gf/internal/model/entity"
)

type (
	IUser interface {
		Register(ctx context.Context, in model.UserRegisterInput) error
		EncryptPassword(password, salt string) string
		Login(ctx context.Context, in model.UserLoginInput) (*entity.User, error)
		UserInfo(ctx context.Context, uid int) (*entity.User, error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
