// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Router is the golang structure for table router.
type Router struct {
	Id        uint        `json:"id"         `
	Path      string      `json:"path"       `
	Name      string      `json:"name"       `
	Redirect  string      `json:"redirect"   `
	Title     string      `json:"title"      `
	Icon      string      `json:"icon"       `
	Component string      `json:"component"  `
	Parent    int         `json:"parent"     `
	OrderNo   int         `json:"order_no"   `
	Status    int         `json:"status"     `
	CreatedAt *gtime.Time `json:"created_at" `
	UpdatedAt *gtime.Time `json:"updated_at" `
	DeletedAt *gtime.Time `json:"deleted_at" `
}
