// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        uint        `json:"id"         `
	Username  string      `json:"username"   `
	Password  string      `json:"password"   `
	Salt      string      `json:"salt"       `
	Nickname  string      `json:"nickname"   `
	Status    int         `json:"status"     `
	CreatedAt *gtime.Time `json:"created_at" `
	UpdatedAt *gtime.Time `json:"updated_at" `
	DeletedAt *gtime.Time `json:"deleted_at" `
}
